# Generated by Django 4.2.1 on 2023-05-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_importante',
            field=models.BooleanField(default=False),
        ),
    ]
