# Generated by Django 4.2.1 on 2023-05-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_usuario_data_importante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='data_importante',
            new_name='datas_importantes',
        ),
    ]
